[pt]
    [[pt.banner]]
    title = "LFM ‘24"
    subtitle1 = "Lisbon Meets Fetish ‘24"
    subtitle2 = "setembro ‘24"
    image = "assets/Banner-hero mobile.png"

[en]
    [[en.banner]]
    title = "LFM ‘24"
    subtitle1 = "Lisbon Meets Fetish ‘24"
    subtitle2 = "september ‘24"
    image = "assets/Banner-hero mobile.png"

[contacts]
    email = "info@gearclubportugal.com"

[socials]
    [socials.facebook]
    id = "gearclubportugal.page"
    
    [socials.instagram]
    id = "gearclubportugal"
    
    [socials.x]
    id = "ClubeGear"
