[pt]
    [[pt.banner]]
    title = "LMF ‘24"
    subtitle1 = "Lisbon Meets Fetish ‘24"
    subtitle2 = "setembro ‘24"
    image = "assets/Banner-hero mobile.png"

[en]
    [[en.banner]]
    title = "LMF ‘24"
    subtitle1 = "Lisbon Meets Fetish ‘24"
    subtitle2 = "september ‘24"
    image = "assets/Banner-hero mobile.png"

[newsletter]
    formUrl = "https://sow6n.mjt.lu/wgt/sow6n/x3ux/form?c=e05debff"
    embebedHelperScript = "https://app.mailjet.com/pas-nc-embedded-v1.js"

[contacts]
    email = "info@gearclubportugal.com"

[socials]
    [socials.facebook]
    id = "gearclubportugal.page"
    
    [socials.instagram]
    id = "gearclubportugal"
    
    [socials.x]
    id = "ClubeGear"
